name: Deploy Bem Facil Fidic - register transaction

on:
    push:
        branches:
            - homolog

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v2

            - name: Use Node.js 20.x
              uses: actions/setup-node@v1
              with:
                  node-version: 20.x

            - name: Install dependencies
              run: yarn install

            - name: Install NPM and run prisma generate
              run: yarn prisma generate

            - name: Build
              run: yarn run build

            - name: Remove dev dependencies
              run: yarn install --production

            - name: Remove unused files
              run: find . -type f -not \( -path './dist/*' -or -path './node_modules/*' -or -name 'package.json' -or -name 'serverless.yml' -or -path './serverless/*' -or -name '.npmrc' \) -delete

            - name: Remove Prisma unused engine
              run: rm -f ./node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node

            - name: List models directory
              run: ls -R models

            - name: Deploy
              uses: serverless/github-action@master
              with:
                  args: deploy --stage hml --verbose
              env:
                  NODE_ENV: production
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  STACK_NAME: bf-fidic-hml
                  AWS_REGION: us-east-1
                  SERVICE_NAME: bf-fidic
                  SLS_DEBUG: 1
